/// Test Type Enumeration Module
///
/// This module defines the types of tests that can be generated by the test
/// service. It provides enumeration values for different test templates and
/// automatic detection capabilities.
library;

/// Types of tests that can be generated.
///
/// This enumeration defines the different test templates available for code
/// generation. Each type corresponds to a specific Mason brick template that
/// generates appropriate test scaffolding for different kinds of Dart code.
///
/// The test service uses this enumeration to determine which template to use
/// when generating test files, either through explicit specification or
/// automatic detection based on source file content.
///
/// Usage:
/// ```dart
/// // Explicit test type specification
/// final request = TestGenerationRequest(
/// targetFile: 'lib/widgets/my_widget.dart',
/// testType: TestType.widget,
/// );
///
/// // Automatic detection
/// final request = TestGenerationRequest(
/// targetFile: 'lib/models/user.dart',
/// testType: TestType.auto, // Will detect as TestType.class_
/// );
/// ```
enum TestType {
  /// Automatically detect based on file content.
  ///
  /// When this value is specified, the test service will analyze the target
  /// file's content to determine the most appropriate test type. The detection
  /// logic looks for Flutter-specific imports and widget class patterns to
  /// distinguish between widget and class tests.
  ///
  /// Detection rules:
  /// * Files containing Flutter imports or widget classes → [TestType.widget]
  /// * All other Dart files → [TestType.class_]
  auto,

  /// Generate Flutter widget test.
  ///
  /// This type generates test scaffolding specifically designed for testing
  /// Flutter widgets. The generated test file includes:
  /// * Flutter test framework imports
  /// * Widget testing utilities and helpers
  /// * Basic widget instantiation and rendering tests
  /// * Pump and settle patterns for widget interaction testing
  ///
  /// Use this type for files containing StatelessWidget, StatefulWidget, or
  /// other Flutter UI components.
  widget,

  /// Generate Dart class test.
  ///
  /// This type generates test scaffolding for general Dart classes and business
  /// logic. The generated test file includes:
  /// * Standard Dart test framework imports
  /// * Basic class instantiation and method testing patterns
  /// * Mock and stub setup for dependency injection
  /// * Common assertion patterns for business logic validation
  ///
  /// Use this type for service classes, data models, utilities, and other
  /// non-UI Dart code.
  class_,
}
