/// Collection of test data and fixtures for CLI testing.
///
/// This class provides commonly used test data such as valid and invalid project names, sample file contents, and
/// other fixtures that are used across multiple test files.
library;

/// Collection of test data and fixtures for CLI testing.
///
/// This class provides commonly used test data such as valid and invalid project names, sample file contents, and
/// other fixtures that are used across multiple test files.
class TestFixtures {
  /// List of valid Dart package names for testing.
  ///
  /// These names follow Dart package naming conventions and should pass validation in the CLI commands.
  static const List<String> validProjectNames = [
    'my_app',
    'flutter_demo',
    'awesome_project',
    'simple',
    'app123',
    'very_long_project_name_with_underscores',
    'test_app_v2',
  ];

  /// List of invalid Dart package names for testing.
  ///
  /// These names violate Dart package naming conventions and should fail validation in the CLI commands.
  static const List<String> invalidProjectNames = [
    'MyApp', // Uppercase letters not allowed
    'my-app', // Hyphens not allowed
    '_private_app', // Cannot start with underscore
    '123app', // Cannot start with number
    'my app', // Spaces not allowed
    'my.app', // Dots not allowed
    '', // Empty string not allowed
    'app-name', // Hyphens not allowed
    'App_Name', // Uppercase not allowed
  ];

  /// List of valid Flutter platform names.
  ///
  /// These correspond to the platforms supported by Flutter and should be accepted by the --platforms flag.
  static const List<String> validPlatforms = [
    'android',
    'ios',
    'web',
    'windows',
    'macos',
    'linux',
  ];

  /// Sample pubspec.yaml content for testing.
  ///
  /// This fixture can be used to create mock Flutter projects or verify that generated projects have correct pubspec
  /// structure.
  static String samplePubspecYaml(String projectName) =>
      '''
name: $projectName
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
''';

  /// Sample main.dart content following MVC pattern.
  ///
  /// This fixture represents the expected structure of a main.dart file generated by the CLI with MVC architecture.
  static const String sampleMainDart = '''
import 'package:flutter/material.dart';
import 'app.dart';

/// Entry point for the Flutter application.
/// 
/// Initializes the app and runs the main application widget.
void main() {
  runApp(const App());
}
''';

  /// Sample app.dart content for MVC architecture.
  ///
  /// This fixture represents the expected structure of an app.dart file that serves as the root application widget
  /// in the MVC pattern.
  static String sampleAppDart(String projectName) =>
      '''
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

import 'screens/home/home_route.dart';
import 'theme/app_theme.dart';

/// Root application widget for $projectName.
/// 
/// Configures the MaterialApp with theme, localization, and routing.
class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '$projectName',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en', ''),
      ],
      home: const HomeRoute(),
    );
  }
}
''';
}
